### ISSUE TITLE
Footer at the bottom of the Page serves no purpose 

### ISSUE THREAD

**Issue by KingMackle** [371team4/371Team4#52]
Footer at the bottom of the Page serves no purpose

## Description

Footer at the bottom of the Page serves no purpose, can we have it removed ?
Use case: 
1. I go to the Slides tab, I have about 10 slides saved 
2. The footer remains fixed and I have to scroll past it 
3. The footer serves no purpose and is present there 
 
## Expected Behavior

Web page should be minimalistic 

## Actual Behavior

Web page has extraneous elements 

## Possible Fix

Remove the Footer component

## Steps to Reproduce

1. Go to the main webpage 

## Context

The footer has no purpose 

## Console log

N/A

## Your Environment

* Version used: Node 9.3
* Browser Name and version: Chrome 64
* Operating System and version (desktop or mobile): Linux

**Comment by ert485** [comment]
+1 for minimalism

**Comment by KingMackle** [comment]
Any updates on this
